---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aodsipam-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aodsipam-service
  template:
    metadata:
      labels:
        app: aodsipam-service
    spec:
      serviceAccount: aodsipam-service
      containers:
      - name: aodsipam-service
        image: {{ .Values.controller.image }}:{{ .Values.controller.tag }}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1