---
apiVersion: v1
kind: Service
metadata:
  name: aodsipam-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: aodsipam-service